### ISSUE TITLE
Add a quick check to see if post has been published

### ISSUE THREAD

**Issue by hirusi** [gocelestial/Celestial#71]
On static sites, there is a lag between submission being created and the site being built. It would be nice to have a button on the success page that checks the HTTP headers on the link page and informs us when the page has been built. This could be automatically done every 10 seconds (up to 10 attempts?) and a manual trigger post that.

This request should be made client-side.

**Comment by hirusi** [comment]
We could pair this with #69

**Comment by hirusi** [comment]
A manual check is available in v0.18.0. A more polished version should be available within a week or two that would automatically keep checking for updates for a set number of attempts.

**Comment by hirusi** [comment]
An automated check is available in v0.20.0. We attempt 36 times at an interval of 5 seconds. Any site that builds in no longer than 2 to 3 minutes should be covered with these defaults.

**Comment by paulrobertlloyd** [comment]
Just posted my first post using Celestial! Worked a treat… though returning to the app I see this conflicting message (the post was successful published): 

<img width="840" alt="Screenshot 2020-11-01 at 15 24 38" src="https://user-images.githubusercontent.com/813383/97807069-a53dfb80-1c56-11eb-83cf-69958ebecfb6.png">

**Comment by hirusi** [comment]
Interesting. If and when you make your next post, could you please take a look at the Network tab in the dev tools? We're really only checking for a 2xx response from the expected post URL if I remember correctly. If your website takes longer than 3ish minutes to build, this check **will fail.** Which is why the language used is a bit ambiguous (_we_ could not determine if the post is live, but it may be!)
